---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: my-java-app
        image: 855879423727.dkr.ecr.us-west-1.amazonaws.com/aws-docker-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
# service type loadbalancer       
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: java-app
#   name: java-app
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   type: LoadBalancer
#   selector:
#     app: java-app